# permissions for end users to view addonconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: addonconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: addonconfig
    app.kubernetes.io/part-of: addonconfig
    app.kubernetes.io/managed-by: kustomize
  name: addonconfig-viewer-role
rules:
- apiGroups:
  - addon.tvs.io
  resources:
  - addonconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addon.tvs.io
  resources:
  - addonconfigs/status
  verbs:
  - get
