---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - addon.tvs.io
  resources:
  - addonconfigdefinitions
  verbs:
  - get
  - list
- apiGroups:
  - addon.tvs.io
  resources:
  - addonconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addon.tvs.io
  resources:
  - addonconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - addon.tvs.io
  resources:
  - addonconfigs/status
  verbs:
  - get
  - patch
  - update
